# Generated by Django 4.2.2 on 2023-12-05 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('student_father_name', models.CharField(max_length=30)),
                ('student_mother_name', models.CharField(max_length=30)),
                ('student_dob', models.DateField()),
                ('upload_document', models.JSONField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ParentsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents_name', models.CharField(max_length=30)),
                ('parents_mobile_no', models.CharField(max_length=10, unique=True)),
                ('parents_email', models.EmailField(max_length=254, unique=True)),
                ('parents_gender', models.CharField(max_length=20)),
                ('parents_DOB', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
