# Generated by Django 4.2.2 on 2023-12-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='upload_document',
            field=models.JSONField(default=list),
        ),
    ]
