# Generated by Django 4.2.2 on 2023-12-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_upload_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='upload_document',
            field=models.JSONField(),
        ),
    ]
