# Generated by Django 4.2.2 on 2023-12-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_parents_parents_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='parents_gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default=1, max_length=10),
        ),
    ]
