# Generated by Django 4.2.2 on 2023-12-06 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_parents_parents_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parents_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parents_name', models.CharField(max_length=30)),
                ('parents_mobile_no', models.CharField(max_length=10, unique=True)),
                ('parents_email', models.EmailField(max_length=254, unique=True)),
                ('parents_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Male', max_length=10)),
                ('parents_DOB', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Parents',
        ),
    ]
